source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'Example' do
  pod 'react-native-drivers-license-barcode-scanner', path: '../../'
  pod 'yoga', path: "../../node_modules/react-native/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: '../../node_modules/react-native', subspecs: [
    'Core',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
end
